// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Routine.Api.Data;

namespace Routine.Api.Migrations
{
    [DbContext(typeof(RoutineDbContext))]
    [Migration("20200817074734_InitData")]
    partial class InitData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Routine.Api.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intruction")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070212"),
                            Intruction = "YoYo Company",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("7ef3c682-6163-4074-85dd-4ab0798fec86"),
                            Intruction = "Niubi de Company",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("141cf996-29a8-4119-a291-d8115ea5c758"),
                            Intruction = "Not good Company",
                            Name = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070211"),
                            Intruction = "YoYo Company",
                            Name = "Microsoft1"
                        },
                        new
                        {
                            Id = new Guid("7ef3c682-6163-4074-85dd-4ab0798fec81"),
                            Intruction = "Niubi de Company",
                            Name = "Google1"
                        },
                        new
                        {
                            Id = new Guid("141cf996-29a8-4119-a291-d8115ea5c751"),
                            Intruction = "Not good Company",
                            Name = "Yahoo1"
                        },
                        new
                        {
                            Id = new Guid("4500eb58-25ae-4d0c-b3c2-1e1df5070212"),
                            Intruction = "YoYo Company",
                            Name = "Microsoft2"
                        },
                        new
                        {
                            Id = new Guid("7ef3c682-6163-4024-85dd-4ab0798fec86"),
                            Intruction = "Niubi de Company",
                            Name = "Google2"
                        },
                        new
                        {
                            Id = new Guid("141cf996-29a8-4129-a291-d8115ea5c758"),
                            Intruction = "Not good Company",
                            Name = "Yahoo2"
                        },
                        new
                        {
                            Id = new Guid("4500eb58-23ae-4d0c-b3cf-1e1df5070212"),
                            Intruction = "YoYo Company",
                            Name = "Microsoft3"
                        },
                        new
                        {
                            Id = new Guid("7ef3c682-6133-4074-85dd-4ab0798fec86"),
                            Intruction = "Niubi de Company",
                            Name = "Google3"
                        },
                        new
                        {
                            Id = new Guid("141cf996-23a8-4119-a291-d8115ea5c758"),
                            Intruction = "Not good Company",
                            Name = "Yahoo3"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ec4c01c-0901-4be0-adea-a18b5ae5f3a5"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070212"),
                            DateOfBirth = new DateTime(1986, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A8L",
                            FirstName = "Lebron",
                            Gender = 1,
                            LastName = "James"
                        },
                        new
                        {
                            Id = new Guid("91c383a5-f359-4573-a456-8bf8dd54827d"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070212"),
                            DateOfBirth = new DateTime(1990, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "No01",
                            FirstName = "赛",
                            Gender = 1,
                            LastName = "田"
                        },
                        new
                        {
                            Id = new Guid("b9489c18-613f-4fd6-abea-c10a53a0be56"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070212"),
                            DateOfBirth = new DateTime(1976, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "G18L",
                            FirstName = "Macheal",
                            Gender = 1,
                            LastName = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("4cd3ebea-f2d6-4595-935c-cf0e7683a6b3"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070212"),
                            DateOfBirth = new DateTime(1989, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "GLA300",
                            FirstName = "Taylor",
                            Gender = 2,
                            LastName = "Swift"
                        },
                        new
                        {
                            Id = new Guid("4e432f7b-778f-4524-9853-4c36f3bd79f8"),
                            CompanyId = new Guid("7ef3c682-6163-4074-85dd-4ab0798fec86"),
                            DateOfBirth = new DateTime(1993, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "C369",
                            FirstName = "Rihanna",
                            Gender = 2,
                            LastName = "Lol"
                        },
                        new
                        {
                            Id = new Guid("30e4ca6b-afef-4df9-b0d9-442037bb7e1b"),
                            CompanyId = new Guid("7ef3c682-6163-4074-85dd-4ab0798fec86"),
                            DateOfBirth = new DateTime(1990, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "No011",
                            FirstName = "赛1",
                            Gender = 1,
                            LastName = "田1"
                        },
                        new
                        {
                            Id = new Guid("88d5dcf1-9113-4b0e-a274-489c6ccb75e7"),
                            CompanyId = new Guid("7ef3c682-6163-4074-85dd-4ab0798fec86"),
                            DateOfBirth = new DateTime(1976, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "G18L1",
                            FirstName = "Macheal1",
                            Gender = 1,
                            LastName = "Jordan1"
                        },
                        new
                        {
                            Id = new Guid("48e060d5-69bb-4ef0-8057-b336660bf949"),
                            CompanyId = new Guid("7ef3c682-6163-4074-85dd-4ab0798fec86"),
                            DateOfBirth = new DateTime(1989, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "GLA3001",
                            FirstName = "Taylor1",
                            Gender = 2,
                            LastName = "Swift1"
                        },
                        new
                        {
                            Id = new Guid("2ca376c1-ae8b-4ca2-a83b-fa3debb2e267"),
                            CompanyId = new Guid("141cf996-29a8-4119-a291-d8115ea5c758"),
                            DateOfBirth = new DateTime(1986, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A8L2",
                            FirstName = "Lebron2",
                            Gender = 2,
                            LastName = "James2"
                        },
                        new
                        {
                            Id = new Guid("68b1e56a-4248-4f11-90fb-d6d8af271896"),
                            CompanyId = new Guid("141cf996-29a8-4119-a291-d8115ea5c758"),
                            DateOfBirth = new DateTime(1990, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "No012",
                            FirstName = "赛2",
                            Gender = 1,
                            LastName = "田2"
                        },
                        new
                        {
                            Id = new Guid("5da80c4e-1624-49ea-9c8e-6f6d8210965f"),
                            CompanyId = new Guid("141cf996-29a8-4119-a291-d8115ea5c758"),
                            DateOfBirth = new DateTime(1976, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "G18L2",
                            FirstName = "Macheal2",
                            Gender = 1,
                            LastName = "Jordan2"
                        },
                        new
                        {
                            Id = new Guid("27711c50-ff3f-440c-a19e-e686b0323228"),
                            CompanyId = new Guid("141cf996-29a8-4119-a291-d8115ea5c758"),
                            DateOfBirth = new DateTime(1989, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "GLA3002",
                            FirstName = "Taylor2",
                            Gender = 2,
                            LastName = "Swift2"
                        },
                        new
                        {
                            Id = new Guid("6ec4c01c-0901-4be0-adea-a18b5ae5f3a1"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070211"),
                            DateOfBirth = new DateTime(1986, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "A8L1",
                            FirstName = "Lebron1",
                            Gender = 1,
                            LastName = "James1"
                        },
                        new
                        {
                            Id = new Guid("91c383a5-f359-4573-a456-8bf8dd548271"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070211"),
                            DateOfBirth = new DateTime(1990, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "No011",
                            FirstName = "赛1",
                            Gender = 1,
                            LastName = "田1"
                        },
                        new
                        {
                            Id = new Guid("b9489c18-613f-4fd6-abea-c10a53a0be51"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070211"),
                            DateOfBirth = new DateTime(1976, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "G18L1",
                            FirstName = "Macheal1",
                            Gender = 1,
                            LastName = "Jordan1"
                        },
                        new
                        {
                            Id = new Guid("4cd3ebea-f2d6-4595-935c-cf0e7683a6b1"),
                            CompanyId = new Guid("4500eb58-25ae-4d0c-b3cf-1e1df5070211"),
                            DateOfBirth = new DateTime(1989, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeNo = "GLA3001",
                            FirstName = "Taylor1",
                            Gender = 2,
                            LastName = "Swift1"
                        });
                });

            modelBuilder.Entity("Routine.Api.Entities.Employee", b =>
                {
                    b.HasOne("Routine.Api.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
